# Assignment 10

### 1. Import the data

In [2]:
import pandas as pd
#from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt 
import chardet

import os
import folium as fm
from folium import Marker, GeoJson
from folium.plugins import MarkerCluster, HeatMap, StripePattern

import geopandas as gpd
from geopandas import GeoSeries
from shapely.geometry import Point, LineString


import branca as br

In [18]:
os.chdir("C:\\Users\\User\\Documents\\GitHub\\Diplomado_PUCP\\Lecture_11\\Assigment_10")

In [16]:
# Reconocemos el encode y reci√©n una vez detectado se abre la base
base = open(r'../../_data/institutos1.csv', 'rb').read()
det = chardet.detect(base)
charenc = det['encoding']
charenc

'ascii'

In [19]:
institutos = pd.read_csv( r'../../_data/institutos1.csv', encoding = charenc)
institutos

,cod_mod,ltimoden_metaatencion,cuentadeid_postulante_procesoadm,sumaden_flagingresante,sumaden_flagmatriculado,ratio,ratio1,dif,dif1,nlat_ie,...,population_ccpp,altitude,Dblock1km,Dblock2km,Dblock3km,Dblock5km,Dblock10km,Dblock20km,Dblock30km,_merge
0,207597,307,481,302,301,0.980456,1.566775,-6,174,-13.52107,...,106400.0,3386.0,14840369,742184,494123,296073,148036,7418,4912,matched (3)
1,207613,240,502,204,204,0.850000,2.091667,-36,262,-13.63997,...,45864.0,2342.0,14970470,748235,499156,299094,149047,7423,4915,matched (3)
2,239970,537,1047,484,476,0.886406,1.949721,-61,510,-15.47827,...,216716.0,3831.0,17000163,850081,566054,340032,170016,8508,5605,matched (3)
3,262311,423,526,353,349,0.825059,1.243499,-74,103,-6.23041,...,23202.0,2358.0,6781025,339512,226341,135205,67102,3351,2234,matched (3)
4,273979,425,544,411,405,0.952941,1.280000,-20,119,-6.49004,...,67362.0,309.0,7070857,353428,235285,141171,70085,3542,2328,matched (3)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1468594,1566,250,241,202,0.128991,0.159642,-1364,-1316,-12.02987,...,579561.0,125.0,13190935,659467,439311,263187,131093,6546,4331,matched (3)
211,1468610,284,74,71,71,0.250000,0.260563,-213,-210,-12.08215,...,66171.0,115.0,13250934,662467,441311,265186,132093,6646,4431,matched (3)
212,1545623,210,266,184,177,0.842857,1.266667,-33,56,-16.13940,...,1175.0,3780.0,17740208,887104,591069,354041,177020,8810,5906,matched (3)
213,1595495,206,144,141,137,0.665049,0.699029,-69,-62,-18.01370,...,86095.0,577.0,19810177,990088,660059,396035,198017,9908,6605,matched (3)
214,1637859,180,134,125,125,0.694444,0.744444,-55,-46,-13.63631,...,45864.0,2392.0,14970469,748234,499156,299093,149046,7423,4915,matched (3)

In [25]:
inst_geo = gpd.GeoDataFrame(institutos, crs = "EPSG:4326", geometry= gpd.points_from_xy(institutos.nlong_ie, institutos.nlat_ie))

In [26]:
shp_dpt = gpd.read_file(r'../../_data/INEI_LIMITE_DEPARTAMENTAL/INEI_LIMITE_DEPARTAMENTAL.shp')

In [27]:
intersct_inst_geo = gpd.overlay(inst_geo, shp_dpt, how = "intersection")

In [28]:
# variables: meta de admisi√≥n, total postulantes, total ingresantes, total matriculados
var_sum = ["ltimoden_metaatencion", "cuentadeid_postulante_procesoadm", "sumaden_flagingresante", "sumaden_flagmatriculado"]

In [31]:
tot_dpt = intersct_inst_geo.groupby(["CCDD"], as_index= False)[var_sum].sum()
#Se hace merge para volver archivo a geopandas
tot_dpt_shp = shp_dpt.merge(tot_dpt, on = "CCDD")

In [32]:
list(tot_dpt_shp.columns)

['OBJECTID_1',
 'OBJECTID',
 'CCDD',
 'NOMBDEP',
 'CAPITAL',
 'Shape_STAr',
 'Shape_STLe',
 'ORIG_FID',
 'Shape_Leng',
 'Shape_Area',
 'CORREO',
 'CONTACTO',
 'WHATSAPP',
 'geometry',
 'ltimoden_metaatencion',
 'cuentadeid_postulante_procesoadm',
 'sumaden_flagingresante',
 'sumaden_flagmatriculado']

In [24]:
#Colorear segun vacantes de institutos

### 2. Import the data